### ISSUE TITLE
Imagenes

### ISSUE THREAD

**Issue by aicelm** [aicelm/aicelm.github.io#1]
@hhkaos
Hola Raúl!
Tengo un problema con las imágenes, no se cargan las que he subido junto con el nuevo CV, me aparece como si no tuviera ninguna,

**Comment by hhkaos** [comment]
Buenas Leticia!, te ha pasado [lo mismo que a Andrea](https://github.com/anmaro13/anmaro13.github.io/issues/1) y que [a Jaime](https://github.com/jaimegc91/jaimegc91.github.io/issues/1).

Te problema se deriva de que WIndows es "[case insensitive](https://en.wikipedia.org/wiki/Case_sensitivity)" (no diferencia entre mayúsculas y minúsculas y los sistemas basados en [Unix](https://en.wikipedia.org/wiki/Unix) (como Linux, Mac, etc) sí. En este caso Github usará seguro Linux como sistema operativo para el servidor que aloja el servidor HTTP.

Un abrazo!
P.D: y por cierto tiene muy buena pinta el CV! 💃

**Comment by aicelm** [comment]
Genial! Ya se ven!

Muchas gracias, me alegro que te vaya gustando ;)
Un abrazo!
